const HttpStatus = {
    CONTINUE: 100,
    SWITCHING_PROTOCOLS: 101,
    PROCESSING: 102,
    CHECKPOINT: 103,

    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NON_AUTHORITATIVE_INFORMATION: 203,
    NO_CONTENT: 204,
    RESET_CONTENT: 205,
    PARTIAL_CONTENT: 206,
    MULTI_STATUS: 207,
    ALREADY_REPORTED: 208,
    IM_USED: 226,

    MULTIPLE_CHOICES: 300,
    MOVED_PERMANENTLY: 301,
    FOUND: 302,


    MOVED_TEMPORARILY: 302,
    SEE_OTHER: 303,
    NOT_MODIFIED: 304,
    USE_PROXY: 305,
    TEMPORARY_REDIRECT: 307,
    PERMANENT_REDIRECT: 308,

    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    PROXY_AUTHENTICATION_REQUIRED: 407,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    PAYLOAD_TOO_LARGE: 413,
    REQUEST_ENTITY_TOO_LARGE: 413,
    URI_TOO_LONG: 414,
    REQUEST_URI_TOO_LONG: 414,
    UNSUPPORTED_MEDIA_TYPE: 415,
    REQUESTED_RANGE_NOT_SATISFIABLE: 416,
    EXPECTATION_FAILED: 417,
    I_AM_A_TEAPOT: 418,
    INSUFFICIENT_SPACE_ON_RESOURCE: 419,
    METHOD_FAILURE: 420,
    DESTINATION_LOCKED: 421,
    UNPROCESSABLE_ENTITY: 422,
    LOCKED: 423,
    FAILED_DEPENDENCY: 424,
    UPGRADE_REQUIRED: 426,
    PRECONDITION_REQUIRED: 428,
    TOO_MANY_REQUESTS: 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
    UNAVAILABLE_FOR_LEGAL_REASONS: 451,

    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    VARIANT_ALSO_NEGOTIATES: 506,
    INSUFFICIENT_STORAGE: 507,
    LOOP_DETECTED: 508,
    BANDWIDTH_LIMIT_EXCEEDED: 509,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
    getStatusText(statusCode) {
        return statusText[statusCode];
    }
};

const statusText = {
    [HttpStatus.CONTINUE]: "Continue",
    [HttpStatus.SWITCHING_PROTOCOLS]: "Switching Protocols",
    [HttpStatus.PROCESSING]: "Processing",
    [HttpStatus.CHECKPOINT]: "Checkpoint",
    [HttpStatus.OK]: "OK",
    [HttpStatus.CREATED]: "Created",
    [HttpStatus.ACCEPTED]: "Accepted",
    [HttpStatus.NON_AUTHORITATIVE_INFORMATION]: "Non-Authoritative Information",
    [HttpStatus.NO_CONTENT]: "No Content",
    [HttpStatus.RESET_CONTENT]: "Reset Content",
    [HttpStatus.PARTIAL_CONTENT]: "Partial Content",
    [HttpStatus.MULTI_STATUS]: "Multi-Status",
    [HttpStatus.ALREADY_REPORTED]: "Already Reported",
    [HttpStatus.IM_USED]: "IM Used",
    [HttpStatus.MULTIPLE_CHOICES]: "Multiple Choices",
    [HttpStatus.MOVED_PERMANENTLY]: "Moved Permanently",
    [HttpStatus.FOUND]: "Found",


    [HttpStatus.MOVED_TEMPORARILY]: "Moved Temporarily",
    [HttpStatus.SEE_OTHER]: "See Other",
    [HttpStatus.NOT_MODIFIED]: "Not Modified",


    [HttpStatus.USE_PROXY]: "Use Proxy",
    [HttpStatus.TEMPORARY_REDIRECT]: "Temporary Redirect",
    [HttpStatus.PERMANENT_REDIRECT]: "Permanent Redirect",
    [HttpStatus.BAD_REQUEST]: "Bad Request",
    [HttpStatus.UNAUTHORIZED]: "Unauthorized",
    [HttpStatus.PAYMENT_REQUIRED]: "Payment Required",
    [HttpStatus.FORBIDDEN]: "Forbidden",
    [HttpStatus.NOT_FOUND]: "Not Found",
    [HttpStatus.METHOD_NOT_ALLOWED]: "Method Not Allowed",
    [HttpStatus.NOT_ACCEPTABLE]: "Not Acceptable",
    [HttpStatus.PROXY_AUTHENTICATION_REQUIRED]: "Proxy Authentication Required",
    [HttpStatus.REQUEST_TIMEOUT]: "Request Timeout",
    [HttpStatus.CONFLICT]: "Conflict",
    [HttpStatus.GONE]: "Gone",
    [HttpStatus.LENGTH_REQUIRED]: "Length Required",
    [HttpStatus.PRECONDITION_FAILED]: "Precondition Failed",
    [HttpStatus.PAYLOAD_TOO_LARGE]: "Payload Too Large",


    [HttpStatus.REQUEST_ENTITY_TOO_LARGE]: "Request Entity Too Large",
    [HttpStatus.URI_TOO_LONG]: "URI Too Long",


    [HttpStatus.REQUEST_URI_TOO_LONG]: "Request-URI Too Long",
    [HttpStatus.UNSUPPORTED_MEDIA_TYPE]: "Unsupported Media Type",
    [HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE]: "Requested range not satisfiable",
    [HttpStatus.EXPECTATION_FAILED]: "Expectation Failed",
    [HttpStatus.I_AM_A_TEAPOT]: "I'm a teapot",


    [HttpStatus.INSUFFICIENT_SPACE_ON_RESOURCE]: "Insufficient Space On Resource",


    [HttpStatus.METHOD_FAILURE]: "Method Failure",


    [HttpStatus.DESTINATION_LOCKED]: "Destination Locked",
    [HttpStatus.UNPROCESSABLE_ENTITY]: "Unprocessable Entity",
    [HttpStatus.LOCKED]: "Locked",
    [HttpStatus.FAILED_DEPENDENCY]: "Failed Dependency",
    [HttpStatus.UPGRADE_REQUIRED]: "Upgrade Required",
    [HttpStatus.PRECONDITION_REQUIRED]: "Precondition Required",
    [HttpStatus.TOO_MANY_REQUESTS]: "Too Many Requests",
    [HttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE]: "Request Header Fields Too Large",
    [HttpStatus.UNAVAILABLE_FOR_LEGAL_REASONS]: "Unavailable For Legal Reasons",
    [HttpStatus.INTERNAL_SERVER_ERROR]: "Internal Server Error",
    [HttpStatus.NOT_IMPLEMENTED]: "Not Implemented",
    [HttpStatus.BAD_GATEWAY]: "Bad Gateway",
    [HttpStatus.SERVICE_UNAVAILABLE]: "Service Unavailable",
    [HttpStatus.GATEWAY_TIMEOUT]: "Gateway Timeout",
    [HttpStatus.HTTP_VERSION_NOT_SUPPORTED]: "HTTP Version not supported",
    [HttpStatus.VARIANT_ALSO_NEGOTIATES]: "Variant Also Negotiates",
    [HttpStatus.INSUFFICIENT_STORAGE]: "Insufficient Storage",
    [HttpStatus.LOOP_DETECTED]: "Loop Detected",
    [HttpStatus.BANDWIDTH_LIMIT_EXCEEDED]: "Bandwidth Limit Exceeded",
    [HttpStatus.NOT_EXTENDED]: "Not Extended",
    [HttpStatus.NETWORK_AUTHENTICATION_REQUIRED]: "Network Authentication Required"
};

module.exports = HttpStatus;